package NareshITcollection;

import java.util.Collections;
import java.util.LinkedHashSet;

public class demolinkedhashset {
    public static void main(String[] args) {
demolinkedhashset lhs= new demolinkedhashset ();
lhs.show ();
    }
    void show(){
        LinkedHashSet lhs= new LinkedHashSet ();
        lhs.add ("vilas");
        lhs.add ('r');
        lhs.add (25);
        lhs.add (25.5f);
        lhs.add (20.235);
        lhs.add (123);
        lhs.add (4);
        // it is not  index based data structure ...
        // heterogeneous data is allowed ...
        // it  is follow  insertion order...
        // it was introduced by java 1.4 version...
        //it is not allow the sorting order ...
        // duplicate values are not applicable...
        //we can add the null value only one  we can add...
        // it is a non synchronized...
        // default capacity is 16 and[ size increase by double ]...
        // underline data structure is  hashtable and linked list...
        // set class we will be having loadfactor  is 0.75% then we can add the data
        // into the set 75% of the size then size  will be increase from double...
        System.out.println (lhs );
//        Collections.sort (lhs);  does not follow the insertion order...

    }
}
